version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    restart: always
    # environment:
    #   GOOGLE_APPLICATION_CREDENTIALS: /key.json
    # volumes:
    #   - ./.credentials/${GOOGLE_APPLICATION_CREDENTIALS}:/key.json:ro
    # env_file: .env
